# Generated by Django 2.2.10 on 2020-04-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creatorId', models.IntegerField(verbose_name='创建人编号')),
                ('subjectId', models.IntegerField(blank=True, null=True, verbose_name='记忆主题编号')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=256, verbose_name='记忆标题')),
                ('picture', models.CharField(blank=True, max_length=256, null=True, verbose_name='图片文件地址')),
                ('audio', models.CharField(blank=True, max_length=256, null=True, verbose_name='音频文件地址')),
                ('content', models.CharField(max_length=256, verbose_name='记忆内容')),
                ('visitor', models.IntegerField(default=0, verbose_name='访问量')),
                ('privacy', models.IntegerField(choices=[(0, '私密记忆'), (1, '公开记忆')], verbose_name='私密/公开记忆')),
                ('activity', models.IntegerField(default=100, verbose_name='活性')),
                ('deathtime', models.IntegerField(default=0, verbose_name='记忆死亡天数')),
            ],
            options={
                'verbose_name': '记忆',
                'verbose_name_plural': '记忆',
                'db_table': 'memory',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='主题')),
                ('createTime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
                'db_table': 'subject',
            },
        ),
    ]
