# Generated by Django 2.2.10 on 2020-04-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_memory_creatorusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='recallTime',
            field=models.IntegerField(default=0, verbose_name='回忆的次数'),
        ),
    ]
