# Generated by Django 2.2.10 on 2020-04-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_memory_recalltime'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='subjectName',
            field=models.CharField(default='', max_length=256, verbose_name='记忆主题名称'),
            preserve_default=False,
        ),
    ]
