# Generated by Django 2.2.10 on 2020-04-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_memory_subjectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='privacy',
            field=models.IntegerField(default=0, verbose_name='私密/公开记忆'),
        ),
    ]
