# Generated by Django 2.2.10 on 2020-05-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0006_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': '咨讯', 'verbose_name_plural': '咨讯'},
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=256, verbose_name='咨讯内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='origin',
            field=models.CharField(max_length=256, verbose_name='咨讯来源'),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.CharField(max_length=256, verbose_name='咨讯图片'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(verbose_name='咨讯时间'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=256, verbose_name='咨讯标题'),
        ),
    ]
