# Generated by Django 2.2.10 on 2020-05-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0007_auto_20200501_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='picture',
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(default='', max_length=256, verbose_name='咨讯作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(default='', verbose_name='咨讯摘要'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(verbose_name='咨讯内容'),
        ),
    ]
