# Generated by Django 2.2.10 on 2020-05-02 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0008_auto_20200501_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order/pho', verbose_name='图片')),
            ],
        ),
    ]
