# Generated by Django 2.2.10 on 2020-05-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='memoryid',
            field=models.IntegerField(default=0, verbose_name='记忆编号'),
            preserve_default=False,
        ),
    ]
