# Generated by Django 2.2.10 on 2020-05-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0010_image_memoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='image', verbose_name='图片'),
        ),
    ]
