# Generated by Django 2.2.10 on 2020-05-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0011_auto_20200502_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.FileField(upload_to='music', verbose_name='音乐')),
                ('memoryid', models.IntegerField(verbose_name='记忆编号')),
            ],
        ),
    ]
